version: '3.2'
services:
    cow-youle:
        image: "swoole:1.9.3"
        volumes:
            - "${HOME}/PHP/new_youle/game/cow_server:/data/swoole"
        networks:
            cow-youle-network:
                ipv4_address: "172.88.88.111"
        ports:
            - "9100:9100"
#        restart: "always"
        command: "php /data/swoole/server.php"
        container_name: "youle-cow-server"

networks:
    cow-youle-network:
        external:
            name: "nginx_nginx-youle-network"
