version: '3.2'
services:
#    redisserver:
#        image: "redis:3.2.8"
#        ports:
#            - "6379:6379"
#        volumes:
##            - type: volume
##              source: /Users/allen/Docker/db/redis
##              target: /data
#            - "/Users/allen/Docker/db/redis:/data"
#            - "/Users/allen/Docker/config/redis:/usr/local/etc/redis"
#            - "/Users/allen/Docker/logs/redis:/var/log/redis/"
#        command: "redis-server /usr/local/etc/redis/redis.conf"
#        labels:
#            name: "redis"
#            role: "redis server"
#        # nginx意外退出时自动重启
#        restart: "always"
#        # 容器名称
#        container_name: "redis-server"

#    memcachedserver:
#        image: "memcached:1.4.35"
#        ports:
#            - "11211:11211"
#        labels:
#            name: "memcached"
#            role: "memcached server"
#        # memcached意外退出时自动重启
#        restart: "always"
#        # 容器名称
#        container_name: "memcached-server"
#
#    mongodbserver:
#        image: "mongo:3.4.2"
#        ports:
#            - "27017:27017"
#        volumes:
#            - "/Users/allen/Docker/db/mongodb:/data/db"
#        # mongo 意外退出时自动重启
#        restart: "always"
#        # 容器名称
#        container_name: "mongodb-server"

    mysqlserver:
        image: "mysql:5.7"
        ports:
            - "3306:3306"
        volumes:
            - "/Users/allen/Docker/db/mysql:/var/lib/mysql"
            - "/Users/allen/Docker/config/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
            - "/Users/allen/Docker/logs/mysql:/var/log/mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=hello123"
        # mysql意外退出时自动重启
        restart: "always"
        # 容器名称
        container_name: "mysql-server"

    phpwebserver:
        # 依赖mysql服务，意味着在启动php之前先启动mysql
        depends_on:
            - "redisserver"
            - "mysqlserver"
        image: "thinkphp:0.2.1"
        links:
            - "mysqlserver:mysqlserver"
            - "mongodbserver:mongodbserver"
            - "redisserver:redisserver"
            - "memcachedserver:memcachedserver"
        volumes:
            - "/Users/allen/webstore:/data/webstore"
        ports:
            - "9000:9000"
        # php意外退出时自动重启
        restart: "always"
        # 容器名称
        container_name: "php-server"

    nginxwebserver:
        # 依赖php服务，意味着在启动nginx之前先启动php
        depends_on:
            - "phpwebserver"
        image: "nginx:1.11"
        ports:
            - "80:80"
            - "443:443"
        links:
            - "phpwebserver:phpwebserver"
        volumes:
            - "/Users/allen/Docker/config/nginx/conf.d:/etc/nginx/conf.d"
            - "/Users/allen/Docker/logs/nginx:/var/log/nginx"
            - "/Users/allen/webstore:/data/webstore"
        # nginx意外退出时自动重启
        restart: "always"
#        volumes_from:
#            - phpwebserver
        # 容器名称
        container_name: "nginx-server"
