version: '3.2'
services:
    hadoop:
        image: "sequenceiq/hadoop-docker:2.7.1"
        ports:
            - "50010:50010"
            - "50020:50020"
            - "50070:50070"
            - "50075:50075"
            - "50090:50090"
            - "8020:8020"
            - "9000:9000"     
            - "10020:10020"
            - "19888:19888"
            - "8030:8030"
            - "8031:8031"
            - "8032:8032"
            - "8033:8033"
            - "8040:8040"
            - "8042:8042"
            - "8088:8088"
            - "49707:49707"
            - "2122:2122"
        volumes:
            - "${HOME}/Docker/logs/hadoop/:/usr/local/hadoop/logs/" 
        container_name: "hadoop"
