version: '3.2'
services:
    redis-master-1:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-master-1:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-master-1:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-master-1:/var/log/redis/"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    redis-master-2:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-master-2:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-master-1:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-master-2:/var/log/redis/"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    redis-slave-1:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-slave-1:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-slave-1:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-slave-1:/var/log/redis/"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    redis-slave-2:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-slave-2:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-slave-2:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-slave-2:/var/log/redis/"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    redis-slave-3:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-slave-3:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-slave-3:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-slave-3:/var/log/redis/"
        links:
            - "redis-master-2:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
    redis-slave-4:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/redis-twemproxy-cluster/redis-slave-4:/data"
            - "/Users/allen/Docker/config/redis-twemproxy-cluster/redis-slave-4:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/redis-twemproxy-cluster/redis-slave-4:/var/log/redis/"
        links:
            - "redis-master-2:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
