version: '3.2'
services:
    redis-master-1:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-master-1:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-master-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-master-1:/var/log/redis/"
        restart: "on-failure:3"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.100"
        container_name: "redis-haproxy-master-1"
    redis-slave-1:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-slave-1:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-slave-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-slave-1:/var/log/redis/"
        restart: "on-failure:3"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.101"
        container_name: "redis-haproxy-slave-1"
    redis-slave-2:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-slave-2:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-slave-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-slave-2:/var/log/redis/"
        restart: "on-failure:3"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.102"
        container_name: "redis-haproxy-slave-2"
    redis-slave-3:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-slave-3:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-slave-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-slave-3:/var/log/redis/"
        restart: "on-failure:3"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.103"
        container_name: "redis-haproxy-slave-3"
    redis-slave-4:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-slave-4:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-slave-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-slave-4:/var/log/redis/"
        restart: "on-failure:3"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.104"
        container_name: "redis-haproxy-slave-4"
    redis-slave-5:
        image: "redis:3.2.8"
        volumes:
            - "/Users/allen/Docker/db/haproxy/redis/redis-slave-5:/data"
            - "/Users/allen/Docker/config/haproxy/redis/redis-slave-conf:/usr/local/etc/redis"
            - "/Users/allen/Docker/logs/haproxy/redis/redis-slave-5:/var/log/redis/"
        restart: "on-failure:3"
        links:
            - "redis-master-1:redis-master"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        networks:
            redis-haproxy-network:
                ipv4_address: "172.10.6.105"
        container_name: "redis-haproxy-slave-5"
networks:
    redis-haproxy-network:
        driver: "bridge"
        ipam:
            driver: "default"
            config:
                - subnet: "172.10.6.0/24"
